### ISSUE TITLE
Add toggle for genes that should be ignored (e.g. repeats)

### ISSUE THREAD

**Issue by RvV1979** [genenotebook/genenotebook#10]
Some gene annotations comprise parts of repetitive elements or may otherwise represent incorrect models. 

It would be good if there was a toggle to indicate that a gene model should be ignored; similar as the pseudogene toggle.

**Comment by holmrenser** [comment]
The updated version of genenotebook has changed the way queries work, so now every attribute can be queries in the same way. This issue should be fixed.
