### ISSUE TITLE
Terminal commands not working for docker installation

### ISSUE THREAD

**Issue by biplabendu** [genenotebook/genenotebook#102]
Thanks for making this. It seems to be the perfect thing I need right now. I installed it using docker (installed perfectly fine, and opens on my localhost port fine as well). The only problem, the genenotebook command doesn't work on my terminal (I am using macOS High Sierra). 

Here is what I did (and worked):
![image](https://user-images.githubusercontent.com/40010307/79059083-f7c8b380-7c43-11ea-8a3a-14eb1f5258e8.png)

This is what I am doing to upload a genome (and the error I get):
**$ genenotebook add genome -u admin -p admin -n test testdata.fasta**
-bash: genenotebook: command not found
(base) 

A few questions?
Q1. Is this the right way for adding genomes upon docker installation? Either way, could you provide a bit more details/instructions on how to do it. (Maybe post a video tutorial, if it's not too much to ask? Complete newbs like me will definitely benefit.)
Q2. I ran the "docker run -p 3000:3000 genenotebook/genenotebook" once, and then closed the terminal. Turns out I can still access the GeneNotebook at localhost:3000. So, do I need to run the command only once on my computer? 

N.B. I used the docker installation since the bioconda had some issues on my computer.

**Comment by holmrenser** [comment]
Hi @biplabendu,

I'm glad that genenotebook seems useful, let's make sure it works on your system! I think what your running into is mainly a lack in documentation.

A1. As genenotebook is running _in_ a docker container, all of the commandline arguments also only work _in_ the docker container. The solution would probably using `docker exec` on the running container, but the genenotebook documentation is currently severely lacking in how to do this.

A2. A bit harder to answer, but I'm guessing the container is running as a daemon in the background. You can get a list of all running containers with `docker ps`. You can then stop any of the running containers with `docker stop CONTAINER_ID`. This seems more of standard docker thing, but nevertheless would be good to cover in the genenotebook documentation.

I'll start with adding some documentation tomorrow!
