### ISSUE TITLE
GeneNotebook doesn't update with the added genome/annotation files

### ISSUE THREAD

**Issue by biplabendu** [genenotebook/genenotebook#103]
I installed GeneNotebook using bioconda in a new conda environment, and that worked.

I am able to push the genome/annotation files (following the example code on your documentation). I also added one of my own genomes in terminal (and it worked). 
See the logs below:
```
$ genenotebook run --port 3300
## LOG: 2020-04-12T03:19:27.643Z Using DB path: /Users/biplabendudas/db
## LOG: 2020-04-12T03:19:27.644Z MongoDB data files are in /Users/biplabendudas/db/data
## LOG: 2020-04-12T03:19:27.645Z MongoDB logs are is in /Users/biplabendudas/db/log
## LOG: 2020-04-12T03:19:27.645Z Starting MongoDB daemon
## LOG: 2020-04-12T03:19:28.745Z GeneNoteBook server started, serving at http://localhost:3300/
## LOG: 2020-04-12T03:19:51.509Z Adding annotation file "/Users/biplabendudas/blast/testdata/testdata.gff" to genome "test"
## LOG: 2020-04-12T03:20:21.844Z addInterproscan
## LOG: 2020-04-12T03:20:21.925Z Encountered fasta section, stopped parsing
## LOG: 2020-04-12T03:20:21.925Z Executing bulk operation
## LOG: 2020-04-12T03:20:21.956Z Finished
## LOG: 2020-04-12T03:22:24.440Z Adding /Users/biplabendudas/blast/GCF_003227725.1_Cflo_v7.5_protein.faa as genome: cflo_v7
```
The problem is that I refreshed the GeneNotebook (on localhost:3300), but nothing shows up on it. Not even the test genome.

Thanks in advance,
Biplabendu

**Comment by holmrenser** [comment]
From the logs it seems like you did not add the genome sequence first, can you confirm this is the case? To properly link a genome with its annotation, genenotebook requires that the genome is loaded first. Definitely something that could be covered more clearly in the documentation!

Also, if your genome is listed as private (default behaviour) and you are not logged in, you will not see it in the browser. Could also use more documentation!

**Comment by biplabendu** [comment]
Hi Rens,

Thanks for getting back to me so promptly. I (and I am sure others as well) would appreciate more documentation. Suggestion: For general users (like me), a video tutorial might be better to see the exact steps in action. I will be looking forward to it.

To answer your questions:
"_From the logs it seems like you did not add the genome sequence first, can you confirm this is the case?_"
I did actually add the test genome (test.fasta) first, and then the annotation file, and so on. I followed the example in your documentation verbatim.
(Note: I should point out, the code for the annotation file in the documentation says ".gff3", but it should be ".gff")

Pushing the files again throws me the following error, telling me the files have been already added. But yet, nothing shows up on the app. Note, all steps were performed post making an account and having logged in.

biplabendudas@MacBook-Pro-5 ~/blast/testdata
$ genenotebook add genome -u admin -p admin -n test testdata.fasta 
bash: genenotebook: command not found
(base) 
biplabendudas@MacBook-Pro-5 ~/blast/testdata
$ conda activate genenotebook
(genenotebook) 
biplabendudas@MacBook-Pro-5 ~/blast/testdata
$ genenotebook add genome -u admin -p admin -n test testdata.fasta 
{ isClientSafe: true,
  error: 'Existing genome: test',
  message: '[Existing genome: test]',
  errorType: 'Meteor.Error' }
(genenotebook) 
biplabendudas@MacBook-Pro-5 ~/blast/testdata
$ genenotebook add annotation -u admin -p admin -n test testdata.gff3
{ isClientSafe: true,
  error: 'Genome test already has an annotation track',
  message: '[Genome test already has an annotation track]',
  errorType: 'Meteor.Error' }
(genenotebook) 
biplabendudas@MacBook-Pro-5 ~/blast/testdata
$ genenotebook add interproscan -u admin -p admin testdata.iprscan.gff3 
Succesfully added 0 protein domains
(genenotebook) 
biplabendudas@MacBook-Pro-5 ~/blast/testdata
$ find . -name "*abundance.tsv" |\
> xargs -n 1 -P 1 -I % sh -c "genenotebook add transcriptome -u admin -p admin %"
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
Succesfully added transcriptome data for 100 genes
(genenotebook) 

Thanks in advance.
