### ISSUE TITLE
Toggling product names does not work as intended

### ISSUE THREAD

**Issue by RvV1979** [genenotebook/genenotebook#11]
behavior: 
When toggling product name to TRUE all genes are selected including the ones with product name = None, when toggling product name to FALSE no genes are selected. 

desired behavior:
When toggling product name to TRUE ony genes with a meaningful product name should be selected,, when toggling product name to FALSE genes with product name = None should be selected.

**Comment by holmrenser** [comment]
The updated version of genenotebook has changed the way queries work, so now every attribute can be queries in the same way. This issue should be fixed.
