### ISSUE TITLE
BulkWriteErrors when importing genome annotations

### ISSUE THREAD

**Issue by Iris95H** [genenotebook/genenotebook#110]
Sometimes BulkWriteErrors show up when importing GFF files:

For example, this one about duplicate keys:
{ isClientSafe: true,
  error: 
   { index: 33427,
     code: 11000,
     errmsg: 'E11000 duplicate key error collection: genenotebook.genes index: c2_ID dup key: { : "undefined_gene_69611_69724" }',
     op: 
      { ID: 'undefined_gene_69611_69724',
        seqid: 'NC_000932.1',
        source: 'RefSeq',
        strand: '-',
        genomeId: 'XcvwFipt3nhe2ZvwB',
        type: 'gene',
        start: 69611,
        end: 69724,
        score: '.',
        attributes: [Object],
        subfeatures: [],
        seq: 'ATACACCCGAGTACATGTTCCTCGTCGCTGAGGGCATCCCCGAAGCGCTGGGGATTTCGTGACGTTTCGGATTGGCTGTCTTGTATTTCTAATAAGTTGTTTAATGGTTGGCAT',
        _id: '5ed8c7ab7ab0440303a35989' },
     name: 'BulkWriteError',
     driver: true,
     err: 
      { index: 33427,
        code: 11000,
        errmsg: 'E11000 duplicate key error collection: genenotebook.genes index: c2_ID dup key: { : "undefined_gene_69611_69724" }',
        op: [Object] },
     result: 
      { ok: 1,
        writeErrors: [Array],
        writeConcernErrors: [],
        insertedIds: [Array],
        nInserted: 33466,
        nUpserted: 0,
        nMatched: 0,
        nModified: 0,
        nRemoved: 0,
        upserted: [] } },
  message: '[BulkWriteError: E11000 duplicate key error collection: genenotebook.genes index: c2_ID dup key: { : "undefined_gene_69611_69724" }]',
  errorType: 'Meteor.Error' }

Or less specific ones:
 { isClientSafe: true,
   error:
    { name: 'BulkWriteError',
      driver: true,
      code: 11000,
      writeErrors:
       [ [Object],
         [Object],
         [Object],
         [Object],
         [Object],
         [Object],
         [Object],
         [Object],
         [Object],
         [Object],
         [Object] ],
      result:
       { ok: 1,
         writeErrors: [Array],
         writeConcernErrors: [],
         insertedIds: [Array],
         nInserted: 55162,
         nUpserted: 0,
         nMatched: 0,
         nModified: 0,
         nRemoved: 0,
         upserted: [] } },
   message: '[BulkWriteError: write operation failed]',
   errorType: 'Meteor.Error' }

**Comment by holmrenser** [comment]
This should be fixed in v0.3.0
