### ISSUE TITLE
CLI command to change administrator password

### ISSUE THREAD

**Issue by mboudet** [genenotebook/genenotebook#218]
Hello!

We are trying to automate the deployment of a genenotebook instance on our end (data loading included).

Would it be possible to add a CLI command to change the administrator password?

(It could be a general command to change an user's password, taking the current admin's credentials as parameters)

**Comment by holmrenser** [comment]
Nice idea! I just published a [new release](https://github.com/genenotebook/genenotebook/releases/tag/v0.3.0) that I want to get into conda. After that I can try to implement this. In the meantime feel free to submit a PR! (I can give some guidance on where to look in the code)

**Comment by mboudet** [comment]
Hello! I'm currently working on this.

As far as I can see, we cannot use the `setUserPassword' route, because it takes an userId (which is not easily findable)

I'm writing another route (`setUsernamePassword` maybe), which will take an username and update the password.

(Still need to work on the return, since `Accounts.setPassword` does not return anything)

For now, the cli is called with `genenotebook user setpassword targetUsername newPassword -u adminUser -p adminPassword`
(That way, we can add other user commands later)

Is this fine with you?

**Comment by holmrenser** [comment]
I had a quick look at your fork (I'm assuming https://github.com/mboudet/genenotebook/commit/7e07b2229ef9beb621acdb417ecf08d8896d1d35 is the most up to date commit). In general your approach for the CLI seems legit. The key thing would be implementing validated server methods that can be triggered from the CLI. By doing this it becomes straightforward to wrap several of the account API calls, including figuring out relevant user IDs (Essentially this would involve doing a DB query).

I'm starting on the validated methods now, with your permission I'll copypaste some of your CLI ideas.

**Comment by mboudet** [comment]
Sure! I just need to deal with the return issue, and I'll submit the PR.
