### ISSUE TITLE
Retire use of settings.json by having account management in CLI

### ISSUE THREAD

**Issue by holmrenser** [genenotebook/genenotebook#225]
The use of settings.json is non-intuitive and leads to some deployment issues. Adapting settings.json in a production environment is not straightforward, and having default account information in settings.json is not very safe.

Some additional discussion in #224 and #218.

Proposed fix: having account management in the CLI means settings.json no longer has to store default accounts.
There should be ways to:

- [x] add account
- [x] remove account
- [x] modify account
- [x] bulk operations of the above (using e.g. json files with account info)

Key consideration: working with passwords on the commandline might not be safe? Genenotebook uses bcrypt to encrypt passwords, could this be used?

**Comment by abretaud** [comment]
LGTM :+1: 
So when creating a new notebook, admin will have to run a cli command to create the first user(s)?

**Comment by holmrenser** [comment]
#2 added most of the desired functionality to retire settings.json. Remaining edge case: new deployments do not have default accounts when settings.json is missing. Tracking in #240

**Comment by holmrenser** [comment]
The settings.json fix was already in place!
