### ISSUE TITLE
Make the uploaded file path configurable

### ISSUE THREAD

**Issue by abretaud** [genenotebook/genenotebook#256]
By default, when uploading files to GNB, they are placed in `/.../genenotebook-0.3.0-0/programs/server/assets/app/uploads/genomeFiles`.
This is a problem for my [Galaxy tool](https://github.com/galaxy-genome-annotation/galaxy-tools/pull/66) as GNB runs in a singularity container meaning that this directory is readonly. To fix it, I would need to change this path to a writable tmp dir.
It would be great to make this path configurable, by using the [storagePath option](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/constructor.md) at https://github.com/genenotebook/genenotebook/blob/master/imports/api/files/fileCollection.js#L6

**Comment by holmrenser** [comment]
I like the idea! I might find some time to implement this next week, stay tuned!

**Comment by holmrenser** [comment]
If we can get this implemented we should be good for a new release!

**Comment by holmrenser** [comment]
Implemented in #288
