### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by mboudet** [genenotebook/genenotebook#291]
Hello,

Currently the search has two issues:

* It does not works (it returns everything no matter what)
* If used from the /genes endpoint, the search bar disappears and need a f5 to come back.

First issue can be fixed easily, there is just an issue with an 'id' not in right div.

I can work on both, but I'd like to have a discussion on the 'search attributes'

Currently, unless the admin has defined 'default search' attributes, the attribute list is empty by default, and the behavior when searching with no attributes is to return everything (which might be a bug?). I feel like this is not clear to the user, since they did write something in the text field.

I'd like to suggest the following:
* If there are no admin-defined 'default search' attributes, all attributes start as selected
* If there are no attributes selected when searching, either
    * We return nothing
    * We behave as if all attributes were selected
    * We block the search until at least one is selected
    * We return everything, but throw a warning? 

Any one of these is fine I think.

Thoughts ? @abretaud @holmrenser

**Comment by holmrenser** [comment]
Ah, good catch. Definitely unwanted behavior that I haven't realized before. I guess it makes sense to have all search attributes enabled by default. Intuitively I think disabling the searchbar when no attributes are selected makes sense, but I'm open to suggestions.

**Comment by mboudet** [comment]
Closed by #292
